### ISSUE TITLE
[BUG] outer layer of skin is over tactical armour

### ISSUE THREAD

**Issue by Finglebottem** [AliensVsPredator/AVP-Regenesis#1]
i dont know if the version im using is the one where you fixed it or not but incase it is and wasnt inflated enought it needs to be inflated a bit more
![image_2024-10-24_225039363](https://github.com/user-attachments/assets/f551cf2e-cfd7-43b5-b02c-05e8c9c9db20)

**Comment by AzureDoom** [comment]
Please report properly with the template.
