### ISSUE TITLE
[Bug]: granite_geode not spawning

### ISSUE THREAD

**Issue by Pheonixatredes** [AliensVsPredator/AVP-Regenesis#17]
### Mod Version

0.0.7

### Mod Loader

Fabric

### Mod Loader Version

checked in place feature command and  in world. granite geode not loading so autunite ore isnt in world. 

### To Reproduce

1.
2.
3.
...

**Comment by Pheonixatredes** [comment]
to reproduce issue use commands to try and generate granite geode but its not listed. 
used ore finder mod to try and locate manually but no autunite generating
located multiple geodes none are granite geode

**Comment by AzureDoom** [comment]
Per discord, its under the ore name. This is done for the sake of consistency
