### ISSUE TITLE
[Bug]: avpr ores not spawning at all

### ISSUE THREAD

**Issue by Pheonixatredes** [AliensVsPredator/AVP-Regenesis#18]
### Mod Version

0.0.7

### Mod Loader

Fabric

### Mod Loader Version

fabric 0.16.7

### Describe the bug

no ore is generating in the 0.0.7 jar. you can have them in inventory and creative menu and existing chunks have it but no new ore spawns. this is most likely what's affecting the geodes spawning as well
![2024-10-27_15 05 11](https://github.com/user-attachments/assets/3e5e03a2-4c90-4e97-b0ef-acb8361e63f2)

### To Reproduce

1.make a new world
2.try to find any avpr ore
3.unable to even with spectator or xray mod
...

**Comment by Pheonixatredes** [comment]
the image is an example of the xray mod i downloaded to test this. it hightlights ore correctly but as you can see there is absolutely no avpr ore anywhere

**Comment by Finglebottem** [comment]
i can confirm no ores are spawning for me either
