### ISSUE TITLE
[Bug]: Predator Shwing noise

### ISSUE THREAD

**Issue by Pheonixatredes** [AliensVsPredator/AVP-Regenesis#31]
### Mod Version

0.0.8

### Mod Loader

Fabric

### Mod Loader Version

0.16.7 fabric

### Describe the bug

two things occure one might not be an intended issue. 
1. when predator goes aggro it makes the schwing noise for when its blades come out. 
2. the sound can be heard very very far away from the predator
3. the sound happens without the blades coming out. noticable on preds holding items. so that might only be the case if they are holding things

### To Reproduce

1.spawn a pred and make something piss it off
2.go far away from it and have something piss it off
3.see if the blades come out when it schwings

**Comment by bvanseg** [comment]
Did not follow issue format/guidelines. Please put only a single bug/complaint in a single issue for future reference.
