### ISSUE TITLE
[Bug]: predator despawns too fast and or not spawning naturally

### ISSUE THREAD

**Issue by Pheonixatredes** [AliensVsPredator/AVP-Regenesis#32]
### Mod Version

0.0.8

### Mod Loader

Fabric

### Mod Loader Version

fabric 0.16.7

### Describe the bug

predators dont seem to be spawning in jungles or savanna or badlands. i waited in these locations for over 30 minutes and no spawns. When they were spawning in previous versions they didnt seem to be spawning 30 blocks apart. When predators are manually spawned in they despawn quickly when they arent supposed to despawn at all. 

### To Reproduce

1.hang out in a predator spawn biome
2.wait for preds
3.if preds never spawn then spawn one with egg
4. move away and return the pred will be gone

**Comment by bvanseg** [comment]
Does not follow issue guidelines. Please split this up into two separate tickets.
