### ISSUE TITLE
[Bug]: Option for alternative weapon fire doesnt work. option for alternative ammo type is missing

### ISSUE THREAD

**Issue by Pheonixatredes** [AliensVsPredator/AVP-Regenesis#35]
### Mod Version

0.0.8

### Mod Loader

Fabric

### Mod Loader Version

fabric 0.16.7

### Describe the bug

in the menu for controls there is no button for alternate ammo types. When hitting the alternate firing mode it doesnt seem to change the firing mode of the weapon. i tested it with the pulse rifle in creative. 

### To Reproduce

1.use pulse rifle
2.hit the alternate fire mode button
3.the mode doesnt seem to change
...

**Comment by bvanseg** [comment]
Does not follow issue guidelines. Please submit two new issues for each distinct bug.
