### ISSUE TITLE
[BUG]boilers spawn at the wrong y level

### ISSUE THREAD

**Issue by Finglebottem** [AliensVsPredator/AVP-Regenesis#5]
![image](https://github.com/user-attachments/assets/c77e3c2c-f644-45fb-8f9c-527f146bf748)
this could have other aliens spawing on the surface i dont know but the boiler should be spawning at i think the negatives not surface

**Comment by Finglebottem** [comment]
Spitters too! y level spawn also needs to be lowered

**Comment by Finglebottem** [comment]
![image](https://github.com/user-attachments/assets/4d569044-ab3a-4cc2-a7fa-783e2e6f762c)
spawning overall is a bit fucked

**Comment by AzureDoom** [comment]
These are using the values from 1.20.4, please adjust via the configuration to find the values, you would find that work best.

**Comment by Pheonixatredes** [comment]
the config file is adjusted and corrected this issue.

**Comment by AzureDoom** [comment]
Fixed per new update
