### ISSUE TITLE
[Bug]: Sword damage is not unique and needs to be changed so they do different damages

### ISSUE THREAD

**Issue by Finglebottem** [AliensVsPredator/AVP-Regenesis#8]
### Mod Version

0.0.4

### Mod Loader

Fabric

### Mod Loader Version

Fabric Loader 1.21.1 Mod version 0.0.4

### Describe the bug

sword damage for the shown weapons needs to be adjusted
![image](https://github.com/user-attachments/assets/913c8788-3b48-4579-aec6-174eba9c79eb)
![image](https://github.com/user-attachments/assets/6dff6158-910d-41f3-b037-6221dd1e2317)
![image](https://github.com/user-attachments/assets/81999c01-9c89-4a85-bc1f-7ed6f23d16f2)
![image](https://github.com/user-attachments/assets/cf1d5f9f-677b-401c-8b59-d64b2ffde025)

### To Reproduce

1. hit things and look at the damage it does?

**Comment by AzureDoom** [comment]
I used the default values from 1.20.4, if a list of values can be given, I can adjust.

**Comment by Finglebottem** [comment]
Sword Values
Orionite: 7.5
aluminium: 5.5
Veritanium: 9
Titanium: 6.5
